### PR TITLE
Applied new file/directory name guidelines #43

### PR DESCRIPTION
**Pull request by RedstoneMedia**
# Description
Implemented the recently merged file and directory name constraints, that were introduced in #43, to the entire project.

## Type of change
- [x] Bug fix (non-breaking change that fixes an issue)

# Checklist
- [x] My code follows the general style guidelines of the project
- I have performed a self-review of my code *(Not applicable, no new code)*
- I have commented my code, particularly where it is unclear *(Not applicable, no new code)*
- [x] My changes generate no new warnings or errors
- [x] The project compiles and runs correctly

### CODE REVIEW

**Comment by Numenter** [comment]
Highly appreciated fundament work, but its looks like you missed some files or are somehow not in the commit.
image

**Review by b7g — CHANGES_REQUESTED** [review]
delete game/menu/emptySzene.tscn
rename game/menu/empty_szene.tscn to game/menu/empty_scene.tscn (referenced in gamemanager.gd:39 and project.godot:48)

**Comment by RedstoneMedia** [comment]
> you missed some files or are somehow not in the commit.

Yeah, sorry once again the files were not renamed in git, but were renamed on my local filesystem. Windows really is annoying sometimes. I just had to `git mv` these files manually. I hope I got all of them now.

**Comment by b7g** [comment]
nearly done.
There are still some (5 errors = 5 tscn?) tscn files within games/sortit that reference
res://shared/fonts/**R**oboto/roboto_black.ttf
but should reference
res://shared/fonts/**r**oboto/roboto_black.ttf

**Review by b7g — APPROVED** [review]

**Pull request merged**
