### PR TITLE
decrease snake speed, because it is too fast

### PR DESCRIPTION
**Pull request by Joshix-1**
the snake is too fast for me. I think it should be slower.

Old:
snake_0067.webm

New:
snake_nice.webm

### CODE REVIEW

**Comment by RedstoneMedia** [comment]
I agree ! For example when the apples are on the edges of the screen it is basically impossible to collect them without dying.

**Comment by Numenter** [comment]
+0.002 seconds don't make much of a difference.
How about 0.125 seconds, that's a nice speed.

**Comment by Joshix-1** [comment]
I think the difference is noticable and improves the expierience a lot

**Comment by Numenter** [comment]
By 60 FPS (0.0166 sec). Your change makes 4 frames to 4 frames (to the next move).
By 144 FPS (0.0069 sec). Your change makes 10 frames to 10 frames.
The noticeable change, is most likely a placebo.

**Comment by RedstoneMedia** [comment]
Wait, the speed shouldn't be different with FPS right ? That's what delta is for.

**Comment by Numenter** [comment]
> Wait, the speed shouldn't be different with FPS right ? That's what delta is for.

Yes.
Frames play a bigger role, because its tick based and not continuous movement.
The change is so small, that its only changes the overflow rate.

Overflow rate is maybe the wrong term.
Each move (4 frames by 60 fps) there is a bit more/less time in the bucket, and on some point it needs one frame less/more to get full.

I'm all for a slower snake, its just to small of a change to make a difference.

**Pull request closed without merging**
