### PR TITLE
Added shared fonts

### PR DESCRIPTION
**Pull request by ASecondGuy**
I thought we are missing shared fonts
That also helps make the text more uniform.

This PR contains these fonts:
[Roboto](https://fonts.google.com/specimen/Roboto)
[Roboto Mono](https://fonts.google.com/specimen/Roboto+Mono)

And these for sparingly used flavor text:
[Caveat](https://fonts.google.com/specimen/Caveat) (Handwriting)
[Press Start 2P](https://fonts.google.com/specimen/Press+Start+2P) (Pixelart Text)

### CODE REVIEW

**Comment by BjoernAkAManf** [comment]
We should not need to use more than three fonts.
A mono font, a serif, a sans serif should be okay.

But i believe even that to be an unnecessary overhead.
Atleast in the context of general purpose font. Can't we just use Roboto Mono and call it a day?

**Comment by ASecondGuy** [comment]
I think a little bit variety is better than too much or too little.
This is the sweet spot I think.

**Comment by ckanitz** [comment]
All Google Fonts are Apache licenced. I'm unsure if that could cause a licence problem since there still seems to be no decision on what licence Suffragium should use.
Perhaps someone who knows about licences could enlighten us?

// Edit
There should also be a reduction in typefaces imho. Let italics calculate and only provide font-types of font-weights of normal, semi-bold and bold or thin, normal and (semi)bold.

**Comment by ASecondGuy** [comment]
> All Google Fonts are Apache licenced. I'm unsure if that could cause a licence problem since there still seems to be no decision on what licence Suffragium should use.

Roboto uses Apache but that isn't a problem as I understand it with [this explenation](https://tldrlegal.com/license/apache-license-2.0-%28apache-2.0%29).
The others use [open font license](https://tldrlegal.com/license/open-font-license-(ofl)-explained) so that sounds fine at least.

**Comment by BjoernAkAManf** [comment]
We should probably link to Roboto and the other fonts respectively. I do think however that we should not include README.txt files from fonts if not actually present.

I changed my negative vote to an upvote now that we only have one font for normal text and two situational fonts.
I don't think it is necessary to include them both, but i don't mind.

**Pull request merged**
