### PR TITLE
Document and reform merge conditions

### PR DESCRIPTION
**Pull request by Numenter**
Created a CONTRIBUTING.md file with reformed merge conditions.
The new conditions should help against low participation in votes.

Related to #8 (issue)

### CODE REVIEW

**Comment by BjoernAkAManf** [comment]
I think we should switch to using the code approval method of github so code changes can not fool votes.

**Comment by Numenter** [comment]
I don't think the approval method should replace the emoji voting. But adding a reviewer requirement is a excellent idea.

**Comment by BjoernAkAManf** [comment]
Emojii voting is flawed. you can't differentiate between a vote before or after a (malicious) change.
Especially when some major restructure or changes are introduced in a PR, that vote may change.

I see no benefit to the emojii voting to be honest, except that it saves two clicks.

**Comment by Numenter** [comment]
And “Request changes” are dislikes than? Or is there another option?
review

**Comment by BjoernAkAManf** [comment]
Pretty much. I assume that most dislikes are mostly due to some minor issues e.g. "Image needs to be changed" or "I'd rather you use that formatting / nameing" rather than "i disagree on a fundamental level". But i concede, that the latter cannot be reasonably expressed through changes. But in that case we could also take into account 👎  as well, because dislikes, unlike likes, are not as dependant on newer changes as their counterpart.

**Comment by Numenter** [comment]
Voting through the review system is growing on me. But this PR is more about the conditions than how to vote. I Would like to take this to a subsequent PR.

**Pull request merged**
