### PR TITLE
added new game: Suffro Mania - 5 min long Mega Man like game

### PR DESCRIPTION
**Pull request by YukkiTimmy**
# Description
Added a new game called "Suffro Mania".
It's a 5 min long Megaman like highscore hunting game. 
Your goal is to kill the boss at the end of the stage with the highest score possible.

grafik

grafik

Please describe the changes you made to the codebase/project files here.
Include all relevant context for the changes and list all new dependencies.
If your change has visual implications on the project, please provide screenshots or animated GIFs of the changes.

Related to # (issue)

## Type of change
- [ ] Bug fix (non breaking change that fixes an issue)
- [ x] New feature (non breaking change that adds functionality)
- [ ] Tooling (non breaking change that adds functionality to the workflow)
- [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)

## Environment
Please describe your environment and remove nonapplicable environment information from this section.
- OS:  Windows
- Hardware: PC
- Software versions:  v3.4.4
- IDE: Godot

## Testing
Please describe the testing you performed on the codebase/project files here and how other users can reproduce your results.

# Checklist
- [ x] My code follows the general style guidelines of the project
- [ x] I have perfomed a self-review of my code
- [ ] I have commented my code, particulary where it is unclear
- [ x] My changes generate no new warnings or errors
- [ x] The project compiles and runs correctly

### CODE REVIEW

**Comment by Joshix-1** [comment]
1. Please respect case when loading scenes. Use everywhere the same case. Case-insensitive loading is bad and doesn't work on every platform. (change main.tscn in game.cfg to Main.tscn)
2. Did you make all these assets on your own?
3. please look at the errors in the Debugger. There are too many new ones
4. make sure to use tools/run_gdtoolkit.py with gdtoolkit to lint and format your changes

**Comment by RedstoneMedia** [comment]
https://opengameart.org/content/space-war-man-platform-shmup-set

sus

I don't see a License or proper attribution. The sprites are licensed under OGA-BY 3.0, which require attribution and the license to be present.
YOU CANNOT SIMPLY COPY SOMEONE's WORK AND DON'T GIVE ATTRIBUTION.

**Comment by YukkiTimmy** [comment]
> https://opengameart.org/content/space-war-man-platform-shmup-set
> 
> sus
> 
> I don't see a License or proper attribution. The sprites are licensed under OGA-BY 3.0, which require attribution and the license to be present. YOU CANNOT SIMPLY COPY SOMEONE's WORK AND DON'T GIVE ATTRIBUTION.

I know that I can't "SIMPLY COPY SOMEONE's WORK ". If you take a look into the Credits, I named all the authors I used the Opensource Art from. 

But I have to admit that i didn't read every paragraph of the text, so I now changed the credit to "Space War Man by Emcee Flesher on opengameart.org", as the author said.

**Comment by YukkiTimmy** [comment]
> 

1. thank you didn't see that!
2. Nope, see the comment below. Like I already said, I gave credit to every author I used the art from.
3. Wanted to fix them later, but did it now!
4. I will totaly do that! 

Thank you for your feedback.

**Comment by RedstoneMedia** [comment]
Again. You did **not** include the `OGA-BY 3.0` License. It needs to be present as a file in the repository (Just like our `LICENSE.md` does too).
Also, the credits for the sprites and music are not easily accessible. They are only shown at the very end, when you manage to beat the game (which is why I couldn't find them at first).

Something else: You might want to consider using `onready var`s more in order to avoid spamming `get_parent().get_parent()` or `get_parent().get_node()` (and other methods of navigating the node tree) everywhere.
Generally, the rule is : If you need a node more than once, add a private variable for it.

Otherwise, the game ain't half bad (although the giant `Main.tscn` is killing me a little, but whatever). Creating such a large map probably takes a lot of time.

**Pull request closed without merging**
