### PR TITLE
I just wanted to change the project icon

### PR DESCRIPTION
**Pull request by KnuTNatioN**
I just wanted to change the project icon so that it stands out more in my craft projects.

### CODE REVIEW

**Comment by ASecondGuy** [comment]
I don't think putting Tom's face on this democratic Project is a good idea.

**Comment by BjoernAkAManf** [comment]
Alternatives:

Very Democratic Much Wow (Pixalated Roman Dude with Sandals and Robe) (¬‿¬).


grafik
grafik

**Comment by MarioLiebisch** [comment]
This would be a perfect example for a local change in your repository in two simple steps:

* Replace the icon with whatever you want it to use (you already did that, obviously).
* Create a new file `.gitignore` (note how the file name start with a `.`) next to the icon file with the following content:

  ```gitignore
  ./.gitignore
  ./icon.png
  ```
Once done, your modified `icon.png` will no longer be listed as an actual uncomitted change to the repository, while you still keep your custom icon.

**Comment by BjoernAkAManf** [comment]
Could be closed in favor of #45

**Pull request closed without merging**
