### PR TITLE
Snake: added color schemes + translations

### PR DESCRIPTION
**Pull request by b7g**
color_selection

Unbenannt

# Description
- adds color schemes and a color scheme selection to games/snake
- adds translations to games/snake
- replaces RichTextLabel with Label in game card and game card info dialog for automatic translations

## Type of change
- [x] New feature (non breaking change that adds functionality)

## Testing
Game functions, translations work.

# Checklist
- [x] My code follows the general style guidelines of the project
- [x] I have perfomed a self-review of my code
- [x] I have commented my code, particulary where it is unclear
- [x] My changes generate no new warnings or errors
- [x] The project compiles and runs correctly

### CODE REVIEW

**Comment by Numenter** [comment]
The select menu looks nice.

Add a mouse hover effect and add arrow key controls (menu).
Some control info text/boxes would be nice too (menu and ingame).

Bug: Game starts in select menu when pressing an arrow key without choosing a scheme.

**Comment by b7g** [comment]
haha, nice catch.
So I will separate it after all.

**Comment by b7g** [comment]
For the control info text boxes I had another idea a week or so ago, but that’s not just for one game.

**Comment by Numenter** [comment]
Should I open an Issue or do you want to fix it here?

Bug: Gameover when changing direction to fast.
Reproduce:
1. Collect min one apple
2. Move right
3. Press fast up or down than left

snake_fast_rotation_death

**Comment by b7g** [comment]
> Should I open an Issue or do you want to fix it here?

yes, no

**Pull request merged**
