### PR TITLE
Enable bbcode

### PR DESCRIPTION
**Pull request by ASecondGuy**
# Description
I think basic formatting or simple text effects in the game descriptions can be a good thing.
If someone doesn't like it they can just ignore it. 

Related to # (issue)

## Type of change
- Bug fix (non breaking change that fixes an issue)
- [x] New feature (non breaking change that adds functionality)
- Tooling (non breaking change that adds functionality to the workflow)
- Breaking change (fix or feature that causes existing functionality to not work as expected)

## Testing
I started the game and played a few minigames

# Checklist
- [x] My code follows the general style guidelines of the project
- [x] I have perfomed a self-review of my code
- [x] I have commented my code, particulary where it is unclear
- [x] My changes generate no new warnings or errors
- [x] The project compiles and runs correctly

### CODE REVIEW

**Comment by b7g** [comment]
This is unnecessary intrusive.

**Comment by Numenter** [comment]
bbcode
First I thought, if it's not hurting someone.
But now, I don't even want to give someone the option to do such things.

**Comment by ASecondGuy** [comment]
Ok, I guess the rainbow wave was too much.

**Comment by Numenter** [comment]
No it was perfect, you opened my eyes.
Bold and maybe underline are codes I can think of that would be useful, but do we even need does?

Can someone give an example, where its better to have BBCode?
I know it's subjective, but a good example would help.

**Comment by RedstoneMedia** [comment]
The only real example that I have (Which only works if the game info card is fully opened) is : Images. These could be usefull to explain the game and its controls. BBcode can display images, but the alignment options are honestly kinda to limiting.

I'm imagining something like this:
image
(From Wii Party)

And this:
image

We definitely won't need rainbow text or strike-through though. I'm pretty sure a custom solution would be better that is more limited (Only **Bold** and maybe underline). For images, I would just use a fixed layout for images, where every game can specify the images to be displayed (Maybe in the game cfg).

**Comment by Numenter** [comment]
A how to play/rules overlay would be a good feature, but its highly game specific and should not be in the description.
Some games are rather complex and would not fit on the info card.

**Comment by RedstoneMedia** [comment]
Yeah that is probably true, but it definitely should be standardized across games.

**Pull request closed without merging**
