### PR TITLE
Pixel Side Scroller: Improve pawn modularity

### PR DESCRIPTION
**Pull request by Numenter**
# Description
Improved modularity of pawn (movement and input modules)

Additionally:
+ added more jump inputs
+ improved and moved out_of_bound logic into map_manager

## Type of change
- [x] Bug fix (non breaking change that fixes an issue)

## Testing
Played Pixel Side Scroller a few times.

### CODE REVIEW

**Comment by RedstoneMedia** [comment]
Note that #87 will probably get merged first. This will cause merge conflicts

**Comment by MarioLiebisch** [comment]
Does this really improve modularity? I understand the idea, making `pawn.input` flexible/replaceable, but not sure it wouldn't be better with some signals, if one wants to decouple things?

**Comment by Numenter** [comment]
Yes, it's an improvement.
“Decouple things” in the sense of disable abilities, like move or jump?
I designed the pawn to always have a movement and input module (in my head). I'm not seeing the point for signals at this point, but hey maybe an example will open my eyes.

**Comment by MarioLiebisch** [comment]
Can try, if I find the time, but I guess it's definitely improving the dependencies for now.🙂

**Pull request merged**
