### PR TITLE
😎 add workflow to look for emojis in commit messages

### PR DESCRIPTION
**Pull request by Joshix-1**
image

### CODE REVIEW

**Comment by ASecondGuy** [comment]
U good?

**Comment by Joshix-1** [comment]
no

**Comment by ASecondGuy** [comment]
Good to know.

**Comment by RedstoneMedia** [comment]
How exactly does this benefit this project ⁉

**Comment by MarioLiebisch** [comment]
Think it's a funny idea, sounds funny on video, but in practice? Not so much. Don't forget not everyone has an emoji button or emoji shortcut etc. and this can actually screw over tools relying on being able to read/print the first lines as plain ANSI text.

**Pull request closed without merging**
