### PR TITLE
branding: added logo & badge, new icon.png

### PR DESCRIPTION
**Pull request by b7g**
# Description
- [x] New feature (non breaking change that adds functionality)

This PR adds a logo badge, a full logo and a new icon.png for the Godot project.
The badge shows a stylised “S” (the first letter of the project name) consisting of an up and a down pointing shape (symbolizing the votes).
suffragium_logo_sp

Related to #38 (pr)

## Environment
- OS: Ubuntu 22.04 LTS
- Software versions: Godot 3.4

## Testing
The project manager shows the new icon.

# Checklist
- [x] My changes generate no new warnings or errors
- [x] The project compiles and runs correctly

### CODE REVIEW

**Comment by Numenter** [comment]
Logo looks OK to me.
There are some unrelated changes committed, remove those.

**Comment by BjoernAkAManf** [comment]
Also update readme with badge.

**Comment by b7g** [comment]
I updated the SVG of the logo, as the text was not converted to path somehow.

Have I restored the files in the correct way?

**Review by BjoernAkAManf — APPROVED** [review]

**Review by Numenter — CHANGES_REQUESTED** [review]
Fulfills all conditions for merge, but has a conflict with main in project.godot.

Try rebase or "Fetch and Merge from main" and fix the conflicts.

**Comment by b7g** [comment]
Well, I think have haven't understood git yet.
Not blaming myself there, tho.

Is this acceptable?

**Comment by Numenter** [comment]
No worries.
Yes, looks fine to me.

**Pull request merged**
