### PR TITLE
Updated Snake's movement handling

### LINKED ISSUE #66: Bug: Snake: Gameover when changing direction to fast
# Description
- [x] Bug Report

Gameover when changing direction to fast.
snake_fast_rotation_death

## Steps to reproduce the issue
1. Open Snake
2. Collect at least one apple
3. Move right
4. Press fast up or down than left

### PR DESCRIPTION
**Pull request by MarioLiebisch**
Added a short input buffer to make tight turns more flexible, also fixing issue #66.

Related to #66

## Type of change
- [x] Bug fix (non breaking change that fixes an issue)

## Testing
Please describe the testing you performed on the codebase/project files here and how other users can reproduce your results.

# Checklist
- [x] My code follows the general style guidelines of the project
- [x] I have perfomed a self-review of my code
- [x] I have commented my code, particulary where it is unclear
- [x] My changes generate no new warnings or errors
- [x] The project compiles and runs correctly

### CODE REVIEW

**Comment by Numenter** [comment]
Not a fan of the scaling, it's too slow at the start and to fast when the precision matters.

The input changes looking good.

**Comment by MarioLiebisch** [comment]
Feel free to suggest a different approach/formula, maybe something more towards quadratic?

**Comment by Numenter** [comment]
Don't like the speed scaling in general, personal preference I guess.
I would rather see more apples (like 3 at the same time) and powerups (positive and negative).

**Comment by Numenter** [comment]
I change my vote, because this an improvement.
Don't like the scaling but its better than the current speed.

**Comment by MarioLiebisch** [comment]
@Joshix-1 Removed the changed difficulty scaling. Does that look better to you?😉

**Pull request merged**
