### PR TITLE
Added Flappy Bird GameMode

### PR DESCRIPTION
**Pull request by heriom**
I added a little flappy bird gamemode.

Maybe it'll be used in the future, maybe not.
I know its not pretty but i just wanted to implement the logic because i am not an artist (i really suck as an artist)

I am using godot now for a short amount of time again (used it in like 2019) and if you see anything changable in the code feel free to change it! And if you have any tips and/or i made mistakes please feel free to message me on discord! heriom#2796

### CODE REVIEW

**Comment by BjoernAkAManf** [comment]
Can we actually use the flappybird image though?

Adding it to the code without proper attribution is also not great.

**Comment by Joshix-1** [comment]
Yes we shouldn't use the flappy bird image. We should make our own.

Besides that here are a few changes I would suggest: https://github.com/Joshix-1/Suffragium/commit/c2c14789740c6714715be670c1231dddb2ef8ed5

**Comment by Numenter** [comment]
Some file changes should not be included in this RP.
Try to revert your commit and include only changes relevant to your minigame.

**Comment by Joshix-1** [comment]
You can just push changes to the flappybird branch. Then this PR gets updated. You don't need to close it

**Comment by heriom** [comment]
@Joshix-1 i wasnt really sure what he meant so i was unsure what to do. my bad

**Comment by Numenter** [comment]
@heriom no no, sorry that i wasn't clear enough. I created a PR on your fork.
https://github.com/heriom/Suffragium/pull/1

**Comment by heriom** [comment]
im going to close this pull request

i opened a new one with the right files

thanks @Numenter!

**Pull request closed without merging**
