### PR TITLE
Tool Script Windows - run GDScript Toolkit

### PR DESCRIPTION
**Pull request by Numenter**
# Description
Added a .bat file for simpler use of the GDScript Toolkit.
Is not important, but maybe some folks want to have it.

## Type of change
- [x] Tooling (non breaking change that adds functionality to the workflow)

## Environment
- OS: Windows

### CODE REVIEW

**Comment by RedstoneMedia** [comment]
Adding `@echo off` might be a good idea.

**Comment by Numenter** [comment]
Maybe something like this?
```
@echo off
cd ..
@echo --- Format ---
gdformat game/
@echo --- Lint ---
gdlint game/
@echo.
@echo.
pause
```
image

**Comment by RedstoneMedia** [comment]
You can remove the "@" from the "--- Format ---" and "--- Lint ---" echo

**Comment by BjoernAkAManf** [comment]
Script could also be a python script at this point. Truely useless without error handling. (Serves no benefit)

I think the intend is great, but i disagree with the solution.

**Comment by ASecondGuy** [comment]
I feel this solution is perfect because right now I have to type those commands myself or write a script of some kind to do those commands for me. This saves some typing. Nothing more nothing less. 
What would error handling even do here? Tell you there was an error like the toolkit already does?

**Comment by BjoernAkAManf** [comment]
Oh right. Perfectly reasonable to introduce a script to save 2 short commands. This is literally why one can create aliases. The script essentially contains bloat and two simple commands.

We could also use earthly too, but its inherently unsafe to use, so we cant use isolation but a locally statement.  

In all honesty this is nothing we need to keep track of. Installation of the tools is more of a concern than defining a trivial script. Im also concerned with inclusion of any platform specific language, because it is not inclusive of new developers. 

Edit: Error handling example: command not available globally or locally due to the dependency not installed.

**Comment by Numenter** [comment]
> Script could also be a python script at this point. 

Yes

**Pull request closed without merging**
